source 'https://rubygems.org'
gem 'kramdown'
gem 'moneta'
gem 'slim', github: 'slim-template/slim', branch: 'master'
gem 'temple', github: 'judofyr/temple', branch: 'master'
gem 'sinatra', '~> 1.4.5'
